- name: "Install MUSL tools and configure environment"
  if: "contains(join(matrix.targets, ' '), 'musl')"
  run: |
    set -xe
    sudo apt-get update
    sudo apt-get install -y build-essential curl musl-tools musl-dev
    wget https://apt.llvm.org/llvm.sh
    sudo chmod +x llvm.sh
    sudo ./llvm.sh 20
    sudo ln -sf /usr/bin/clang-20 /usr/bin/clang
    sudo ln -sf /usr/bin/clang++-20 /usr/bin/clang++
    sudo ln -sf /usr/bin/lld-20 /usr/bin/lld

    clang --version

    echo "CC_x86_64_unknown_linux_musl=clang" >> $GITHUB_ENV
    echo "CXX_x86_64_unknown_linux_musl=clang++" >> $GITHUB_ENV
    echo "AR_x86_64_unknown_linux_musl=llvm-ar" >> $GITHUB_ENV
    echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=clang" >> $GITHUB_ENV
    echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUSTFLAGS=-C link-arg=-fuse-ld=lld -C target-feature=+crt-static" >> $GITHUB_ENV

    echo "LDFLAGS=-static $LDFLAGS" >> $GITHUB_ENV
    echo "CFLAGS=-I/usr/include/x86_64-linux-musl $CFLAGS -O2 -static" >> $GITHUB_ENV
    echo "CXXFLAGS=-I/usr/include/x86_64-linux-musl $CXXFLAGS -O2 -static" >> $GITHUB_ENV
    echo "LD_LIBRARY_PATH=/usr/lib/x86_64-linux-musl:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-musl/pkgconfig" >> $GITHUB_ENV
