use crate::{
    config::Project,
    ext::eyre::CustomWrapErr,
    internal_prelude::*,
};
use base64ct::{Base64UrlUnpadded, Encoding};
use camino::Utf8PathBuf;
use eyre::{ContextCompat, Result};
use md5::{Digest, Md5};
use std::{collections::HashMap, fs};

///Adds hashes to the filenames of the css, js, and wasm files in the output
pub fn add_hashes_to_site(proj: &Project) -> Result<()> {
    let files_to_hashes = compute_front_file_hashes(proj).dot()?;

    debug!("Hash computed: {files_to_hashes:?}");

    let renamed_files = rename_files(&files_to_hashes).dot()?;
    let pkg_dir = proj.site.root_relative_pkg_dir();

    replace_in_file(
        &renamed_files[&proj.lib.js_file.dest],
        &renamed_files,
        &pkg_dir,
        false,
    );

    let wasm_split_hash = if proj.split {
        // The loader is emitted at a stable `__wasm_split.js` name (see
        // `wasm_split_tools`). Rewrite the chunk / split / main-module references
        // inside it to their hashed names *first*, then hash the final bytes so
        // the loader's cache key actually tracks the chunks it loads.
        let loader = pkg_dir.join("__wasm_split.js");
        replace_in_file(&loader, &renamed_files, &pkg_dir, false);

        let hash = Base64UrlUnpadded::encode_string(
            &Md5::new().chain_update(fs::read(&loader)?).finalize(),
        );
        let hashed_loader = pkg_dir.join(format!("__wasm_split.{hash}.js"));
        fs::rename(&loader, &hashed_loader)
            .wrap_err_with(|| format!("Failed to rename {loader} to {hashed_loader}"))?;

        // The main JS/WASM import the stable `./__wasm_split.js` specifier, which
        // is never hashed. Emit a tiny shim there that re-exports the
        // content-hashed loader: the shim is the only artifact that must be
        // revalidated, while the real loader (and the chunks) stay immutable.
        fs::write(
            &loader,
            format!("export * from \"./__wasm_split.{hash}.js\";\n"),
        )
        .wrap_err_with(|| format!("Failed to write wasm-split shim to {loader}"))?;

        // The prefetch manifest references chunks by their pre-hash names
        // (without extension); rewrite those to match the renamed chunk files.
        if let Some(manifest) = renamed_files.values().find(|p| {
            p.file_name()
                .is_some_and(|f| f.starts_with("__wasm_split_manifest"))
        }) {
            replace_in_file(manifest, &renamed_files, &pkg_dir, true);
        }

        Some(hash)
    } else {
        None
    };

    let manifest_file = files_to_hashes
        .iter()
        .find_map(|(f, h)| (f.ends_with("__wasm_split_manifest.json")).then_some(h));
    let manifest_file = manifest_file
        .map(|f| format!("manifest: {f}\n"))
        .unwrap_or_default();
    let wasm_split_file = wasm_split_hash
        .map(|f| format!("split: {f}\n"))
        .unwrap_or_default();

    fs::create_dir_all(
        proj.hash_file
            .abs
            .parent()
            .wrap_err_with(|| format!("no parent dir for {}", proj.hash_file.abs))?,
    )
    .wrap_err_with(|| format!("Failed to create parent dir for {}", proj.hash_file.abs))?;

    fs::write(
        &proj.hash_file.abs,
        format!(
            "{}: {}\n{}: {}\n{}: {}\n{}{}",
            proj.lib
                .js_file
                .dest
                .extension()
                .ok_or(eyre!("no extension"))?,
            files_to_hashes[&proj.lib.js_file.dest],
            proj.lib
                .wasm_file
                .dest
                .extension()
                .ok_or(eyre!("no extension"))?,
            files_to_hashes[&proj.lib.wasm_file.dest],
            proj.style
                .site_file
                .dest
                .extension()
                .ok_or(eyre!("no extension"))?,
            files_to_hashes[&proj.style.site_file.dest],
            manifest_file,
            wasm_split_file
        ),
    )
    .wrap_err_with(|| format!("Failed to write hash file to {}", proj.hash_file.abs))?;

    debug!("Hash written to {}", proj.hash_file.abs);

    Ok(())
}

fn compute_front_file_hashes(proj: &Project) -> Result<HashMap<Utf8PathBuf, String>> {
    let mut files_to_hashes = HashMap::new();

    let mut stack = vec![proj.site.root_relative_pkg_dir().into_std_path_buf()];

    while let Some(path) = stack.pop() {
        if let Ok(entries) = fs::read_dir(path) {
            for entry in entries.flatten() {
                let path = entry.path();

                if path.is_file() {
                    if let Some(extension) = path.extension() {
                        if extension == "css" && path != proj.style.site_file.dest {
                            continue;
                        }
                    }

                    // We do not want to hash files generated by webassembly
                    // in the snippets folder as the webassembly will look for
                    // unhashed versions of the .js files. The folder though can be hashed.
                    if let Some(path_str) = path.to_str() {
                        if path_str.contains("snippets") && path.is_file(){
                            continue;
                        }
                    }

                    // The wasm-split loader keeps a stable, un-hashed name so the
                    // main JS/WASM can import it without their bytes being patched.
                    // It is hashed and shimmed separately in `add_hashes_to_site`.
                    if path.file_name().and_then(|f| f.to_str()) == Some("__wasm_split.js")
                    {
                        continue;
                    }

                    let hash = Base64UrlUnpadded::encode_string(
                        &Md5::new().chain_update(fs::read(&path)?).finalize(),
                    );

                    if path
                        .file_stem()
                        .and_then(|name| name.to_str())
                        .is_some_and(|name| name == hash)
                    {
                        continue;
                    }

                    files_to_hashes.insert(
                        Utf8PathBuf::from_path_buf(path).expect("invalid path"),
                        hash,
                    );
                } else if path.is_dir() {
                    stack.push(path);
                }
            }
        }
    }

    Ok(files_to_hashes)
}

fn rename_files(
    files_to_hashes: &HashMap<Utf8PathBuf, String>,
) -> Result<HashMap<Utf8PathBuf, Utf8PathBuf>> {
    const HASH_PLACEHOLDER: &str = "______________________";
    let mut old_to_new_paths = HashMap::new();

    for (path, hash) in files_to_hashes {
        let mut new_path = path.clone();

        let file_name = new_path.file_name().unwrap_or_default();

        let new_file_name = if file_name.contains(HASH_PLACEHOLDER) {
            if hash.len() != HASH_PLACEHOLDER.len() {
                return Err(anyhow!(
                    "File hash length did not match placeholder hash length."
                ));
            }
            file_name.replace(HASH_PLACEHOLDER, hash)
        } else {
            format!(
                "{}.{}.{}",
                path.file_stem().ok_or(eyre!("no file stem"))?,
                hash,
                path.extension().ok_or(eyre!("no extension"))?,
            )
        };

        new_path.set_file_name(new_file_name);

        fs::rename(path, &new_path)
            .wrap_err_with(|| format!("Failed to rename {path} to {new_path}"))?;

        old_to_new_paths.insert(path.clone(), new_path);
    }

    Ok(old_to_new_paths)
}

fn replace_in_file(
    path: &Utf8PathBuf,
    old_to_new_paths: &HashMap<Utf8PathBuf, Utf8PathBuf>,
    root_dir: &Utf8PathBuf,
    omit_extension: bool,
) {
    let mut contents = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("error {e}: could not read file {path}"));

    for (old_path, new_path) in old_to_new_paths {
        let old_path = old_path
            .strip_prefix(root_dir)
            .expect("could not strip root path");
        let new_path = new_path
            .strip_prefix(root_dir)
            .expect("could not strip root path");

        if omit_extension {
            let old_path = old_path.as_str().trim_end_matches(".wasm");
            let new_path = new_path.as_str().trim_end_matches(".wasm");
            contents = contents.replace(old_path, new_path);
        } else {
            contents = contents.replace(old_path.as_str(), new_path.as_str());
        }
    }

    fs::write(path, contents).expect("could not write file");
}
